config/routes.rb
Rails.application.routes.draw do
  # devise記載変更
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  #
  # 顧客用
  scope module: :public do
    # homes
    root to: "homes#top"
    get "about" => "homes#about", as: "about"
    # products
    resources :products, only: [:index,:show]
    get "searches" => "products#searches"
    get "search_word" => "products#search_word"
    # customers
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get "customers/unsubscribe" => "customers#unsubscribe",as:"unsubscribe"
    patch "customers/withdrawal" => "customers#withdrawal",as:"withdrawal"
    # cart_items
    resources:cart_items, only: [:index, :update, :destroy, :create] do
      delete "cart_items/destroy_all" => "cart_items#destroy_all",as:"destroy_all"
    end
    # orders
    resources :orders, only: [:new, :create, :index]
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "orders/complete" => "orders#complete", as: "complete"
    get "orders/:id" => "orders#show", as: "order"
    # shipping_address
    resources :shipping_addresses
  end
  #
  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    resources :products
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products

  def self.search_for(content)
    genres = Genre.where("genre LIKE?", "#{content}")
    genres.inject(init = []){|result, genre| result + genre.products}
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    if genre.save
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    if genre.update(genre_params)
      redirect_to admin_genres_path
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:genre)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="mt-4">
    <div class="col-12 col-lg-6">

      <h2>ジャンル一覧・追加</h2>
      <div class="mt-4">
        <!--ジャンル名登録フォーム-->
        <%= form_with model: @genre, url: admin_genres_path, local:true do |f| %>
          <%= f.label :genre, 'ジャンル名' %>
          <%= f.text_field :genre %>
          <%= f.submit '新規投稿', class:"btn btn-sm btn-success" %>
        <% end %>
      </div>

      <!--既に登録されているジャンルのリスト-->
      <div class="mt-4">
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th>ジャンル</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
            <tr>
              <td><p><%= genre.genre %></p></td>
              <td><%= link_to '編集', edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>