config/routes.rb
Rails.application.routes.draw do
  # devise記載変更
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  #
  # 顧客用
  scope module: :public do
    # homes
    root to: "homes#top"
    get "about" => "homes#about", as: "about"
    # products
    resources :products, only: [:index,:show]
    get "searches" => "products#searches"
    get "search_word" => "products#search_word"
    # customers
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get "customers/unsubscribe" => "customers#unsubscribe",as:"unsubscribe"
    patch "customers/withdrawal" => "customers#withdrawal",as:"withdrawal"
    # cart_items
    resources:cart_items, only: [:index, :update, :destroy, :create] do
      delete "cart_items/destroy_all" => "cart_items#destroy_all",as:"destroy_all"
    end
    # orders
    resources :orders, only: [:new, :create, :index]
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "orders/complete" => "orders#complete", as: "complete"
    get "orders/:id" => "orders#show", as: "order"
    # shipping_address
    resources :shipping_addresses
  end
  #
  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    resources :products
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    self.last_name + " " + self.first_name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :quantity, presence: true

  def sub_total
    quantity*product.with_tax_price
  end

  def quantity_options
    options = []
    (self.quantity + 11).times do |count|
      options << [count, count]
    end
    return options
  end

  def self.total_price(customer)
    CartItem.where(customer_id: customer.id).inject(0){|sum, cart_item| sum + cart_item.sub_total}
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def address_display
    '〒　' + post_code + ' ' + address + ' ' + last_name + ' ' + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products

  def self.search_for(content)
    genres = Genre.where("genre LIKE?", "#{content}")
    genres.inject(init = []){|result, genre| result + genre.products}
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum method_of_payment: {credit_card: 0, transfer: 1}
  enum order_status: {waiting: 0, confirmation: 1, production: 2, preparing: 3, shipped: 4}

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
  enum making_status: {can_not_start: 0, waiting_for_production: 1, production: 2, completed: 3}

  def sub_total
    quantity*product.with_tax_price
  end

  def self.total_price(order)
    OrderDetail.where(order_id: order.id).inject(0){|sum, order_detail| sum + order_detail.sub_total}
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre

  has_one_attached :product_image

  validates :prise, presence: true
  validates :product_image, presence: true

  def get_product_image
    unless product_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      product_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    product_image
  end

  def with_tax_price
    tax = 1.1
    (price*tax).floor
  end
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :phone_number, presence: true

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def new
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    if genre.save
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    if genre.update(genre_params)
      redirect_to admin_genres_path
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:genre)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page])
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-5 bg-info text-white">
  <div class="container">
    <div class="row">
      <div class="col-9 mt-4">
        <h1>お店屋さん</h1>
        <p>お店屋さんはやっています。</p>
      </div>
      <div class="col-3 mt-4 text-right">
        <ul class="list-group list-unstyled">
          <li class="list-grpup-item">aaaaa</li>
          <li class="list-grpup-item">bbbbb</li>
          <li class="list-grpup-item">ccccc</li>
        </ul>
      </div>
      <div class="col-12 mt-3">
        <p class="text-center">shop replay</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-info text-white">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">

      <a class="navbar-brand p-3" href="/">ロゴ</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "新規登録", "/", class:'nav-link text-white' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", "/", class:'nav-link text-white' %>
          </li>
        </ul>
        <!--一旦判定用-->
        <% if customer_signed_in? %>
        カスタマーログイン中
        <% elsif admin_signed_in? %>
        アドミンログイン中
        <% else %>
        ゲストアクセス中
        <% end %>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopRe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>